version: '3.4'

services:
  basketdb:
    image: mongo
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Basket.API/Dockerfile